name: 'Default Update'
description: 'Default Update Flow'
inputs:
  name:
    required: true
  access_token:
    required: true
  markdown_url:
    required: true
  filename:
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Git
      shell: bash
      run: |
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git config --global user.name 'github-actions[bot]'

    - name: Clone the repository and checkout to branch
      shell: bash
      run: |
        REPOSITORY_URL="https://${GITHUB_ACTOR}:${{ inputs.access_token }}@github.com/${GITHUB_REPOSITORY}.git"
        git clone "${REPOSITORY_URL}" repository
        cd repository
        git branch -a
        git checkout markdowns

    - name: Update ${{ inputs.name }}
      shell: bash
      run: |
        set -eux
        curl -L '${{ inputs.markdown_url }}' > 'repository/${{ inputs.filename }}'
        python3 add_badges.py 'repository/${{ inputs.filename }}'
        cd repository
        git pull
        git add '${{ inputs.filename }}'
        git commit -m 'updated ${{ inputs.filename }}' && git push || true

