name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'

      - name: Clone the repository and checkout to the branch
        run: |
          REPOSITORY_URL="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git clone "${REPOSITORY_URL}" repository
          cd repository
          git branch -a
          git checkout markdowns

      - name: Update
        run: |
          set -eux
          FILENAMES=`node index.js repository`
          cd repository
          for FILENAME in $FILENAMES
          do
            git add "$FILENAME"
            git commit -m "[bot] updated $FILENAME" || true
          done
          git push || true
