name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '* * * * *'

  workflow_dispatch:

jobs:
  update-awesome-go:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/default-update
        with:
          name: Awesome Go
          access_token: ${{ secrets.ACCESS_TOKEN }}
          markdown_url: 'https://raw.githubusercontent.com/avelino/awesome-go/master/README.md'
          filename: 'awesome-go.md'
               
  update-awesome-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/default-update
        with:
          name: Awesome Python
          access_token: ${{ secrets.ACCESS_TOKEN }}
          markdown_url: 'https://raw.githubusercontent.com/vinta/awesome-python/master/README.md'
          filename: 'awesome-python.md'
      
  update-awesome-php:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/default-update
        with:
          name: Awesome PHP
          access_token: ${{ secrets.ACCESS_TOKEN }}
          markdown_url: 'https://raw.githubusercontent.com/ziadoz/awesome-php/master/README.md'
          filename: 'awesome-php.md'
     
